### PR TITLE
Replace forEach with for of loops

### PR DESCRIPTION
**Pull request by StorytellerCZ**
Having issues with @zodern types when trying to publish:
```
meteor publish
[zodern:types] => Cleaning old generated types
[zodern:types] => Generating package type declaration files
node_modules/@types/meteor/mongo.d.ts:268:46 - error TS2344: Type 'T' does not satisfy the constraint '{ [key: string]: any; }'.
...
```

### CODE REVIEW

**Review by jankapunkt — APPROVED** [review]

**Comment by StorytellerCZ** [comment]
@jankapunkt can you please try if you can release this? As mentioned above I'm having an issue with `zodern:types` stopping the release.

**Comment by jankapunkt** [comment]
@StorytellerCZ `  api.versionsFrom('2.0');` might this be the issue?

**Comment by jankapunkt** [comment]
From what I see this is referring to mongo so it might be a core issue and this you may try a newer `api.versionsFrom('2.0')`

**Comment by jankapunkt** [comment]
published with `api.versionsFrom(['2.8.0']);` seemed to do the trick

**Pull request merged**
